# EnvType = mario
# EnvID = SuperMarioBros-v0
# MaxStepPerEpisode = 18000

# MontezumaRevengeNoFrameskip-v4
# BreakoutNoFrameskip-v4

[DEFAULT]

EnvType = atari
EnvID = BreakoutNoFrameskip-v4
MaxStepPerEpisode = 4500

LearningRate = 0.00025
Gamma = 0.99
UseGPU = True
MiniBatch = 32
StickyAction = False
ActionProb = 0.25
LifeDone = False
ObsNormStep = 1

[OPTIONS]
EnvType = [atari, mario]
